package com.united.sample.drools;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;




/**
 * This class was automatically generated by the data modeler tool.
 */

public class PaxSegment implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public PaxSegment() {
    }

    private List<SSR> SSR;
    private String FlightNumber;
    private String Origin;
    private String Destination;
    private String ScheduledDepartureDate;

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        PaxSegment that = (PaxSegment) o;
        return Objects.equals(getFlightNumber(), that.getFlightNumber()) &&
                Objects.equals(getOrigin(), that.getOrigin()) &&
                Objects.equals(getDestination(), that.getDestination()) &&
                Objects.equals(getScheduledDepartureDate(), that.getScheduledDepartureDate());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getSSR(), getFlightNumber(), getOrigin(), getDestination(), getScheduledDepartureDate());
    }

    public List<com.united.sample.drools.SSR> getSSR() {
        return SSR;
    }

    public void setSSR(List<com.united.sample.drools.SSR> SSR) {
        this.SSR = SSR;
    }

    public String getFlightNumber() {
        return FlightNumber;
    }

    public void setFlightNumber(String flightNumber) {
        FlightNumber = flightNumber;
    }

    public String getOrigin() {
        return Origin;
    }

    public void setOrigin(String origin) {
        Origin = origin;
    }

    public String getDestination() {
        return Destination;
    }

    public void setDestination(String destination) {
        Destination = destination;
    }

    public String getScheduledDepartureDate() {
        return ScheduledDepartureDate;
    }

    public void setScheduledDepartureDate(String scheduledDepartureDate) {
        ScheduledDepartureDate = scheduledDepartureDate;
    }

    public static void populateNewPAXSegment(Passenger passenger) {
        ArrayList PaxSegmentList = new ArrayList<PaxSegment>();
        PaxSegment paxSegment = new PaxSegment();
        paxSegment.setFlightNumber("22334");
        paxSegment.setDestination("NCY");
        paxSegment.setOrigin("PHX");
        paxSegment.setScheduledDepartureDate("11/24/2021");
        ArrayList SSRList = new ArrayList<SSR>();

        SSR ssr= new SSR("C234","CO456","R456","I567");
        SSRList.add(ssr);
        paxSegment.setSSR(SSRList);

        PaxSegmentList.add(paxSegment);
        passenger.setPaxSegments(PaxSegmentList);
    }

    public static void populateOLDPAXSegment(Passenger passenger) {
        ArrayList PaxSegmentList = new ArrayList<PaxSegment>();
        // PAX 1
        PaxSegment paxSegment = new PaxSegment();
        paxSegment.setFlightNumber("OLD-22334");
        paxSegment.setDestination("OLD-NCY");
        paxSegment.setOrigin("OLD-PHX");
        paxSegment.setScheduledDepartureDate("11/24/2021");
        ArrayList SSRList = new ArrayList<SSR>();
        ArrayList SSRList2 = new ArrayList<SSR>();


        // PAX 2
        PaxSegment paxSegment2 = new PaxSegment();
        paxSegment2.setFlightNumber("OLD-22334/2");
        paxSegment2.setDestination("OLD-NCY/2");
        paxSegment2.setOrigin("OLD-PHX/2");
        paxSegment2.setScheduledDepartureDate("11/24/2021");


        SSR ssr2= new SSR("O-C234-2","O-CO456-2","O-R456","O-I567");
        SSRList2.add(ssr2);
        SSR ssr= new SSR("O-C234","O-CO456","O-R456","O-I567");
        SSRList.add(ssr);
        paxSegment2.setSSR(SSRList2);
        paxSegment.setSSR(SSRList);

        PaxSegmentList.add(paxSegment);
        PaxSegmentList.add(paxSegment2);
        passenger.setPaxSegments(PaxSegmentList);

    }

}