package com.united.sample.drools;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PNRGroup implements java.io.Serializable {

    private String pnrType;
    private List<Passenger> passengers;
    private List<FlightSegment> flightSegments;


    static final long serialVersionUID = 1L;

    public PNRGroup() {
        
        
        
    }
    
    public String getPnrType() {
        return pnrType;
    }

    public void setPnrType(String pnrType) {
        this.pnrType = pnrType;
    }

    public List<Passenger> getPassengers() {
        return passengers;
    }

    public void setPassengers(List<Passenger> passengers) {
        this.passengers = passengers;
    }

    public List<FlightSegment> getFlightSegments() {
        return flightSegments;
    }

    public void setFlightSegments(List<FlightSegment> flightSegments) {
        this.flightSegments = flightSegments;
    }
    
     @Override
    public String toString() {
        return "PNRGroup{" +
                "pnrType='" + pnrType + '\'' +
                ", passengers=" + passengers +
                ", flightSegments=" + flightSegments +
                '}';
    }



}