package com.united.sample.drools;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PNRGroup implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public PNRGroup() {
    }




}