package com.myspace.DevWorkflow;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PaxSegment implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public PaxSegment() {
    }




}